CREATE TABLE `keys` (
  `key` VARCHAR(256) NOT NULL UNIQUE,
  owner VARCHAR(64) NOT NULL,
  name VARCHAR(32) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`key`),
  INDEX owner (owner),
  INDEX created (created)
);

CREATE TABLE reqs (
  `key` VARCHAR(256) NOT NULL,
  app VARCHAR(32) NOT NULL,
  total INT(12) NOT NULL DEFAULT 0,
  last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key`, app),
  INDEX total (total)
);

CREATE TABLE reqs_daily (
  `key` VARCHAR(256) NOT NULL,
  app VARCHAR(32) NOT NULL,
  day VARCHAR(32) NOT NULL,
  total INT(12) NOT NULL DEFAULT 0,
  PRIMARY KEY (`key`, day, app),
  INDEX total (total)
);

CREATE TABLE reqs_monthly (
  `key` VARCHAR(256) NOT NULL,
  app VARCHAR(32) NOT NULL,
  month VARCHAR(32) NOT NULL,
  total INT(12) NOT NULL DEFAULT 0,
  PRIMARY KEY (`key`, month, app),
  INDEX total (total)
);
