CREATE TABLE `keys` (
  id INT AUTO_INCREMENT primary key NOT NULL,
  `key` VARCHAR(32) NOT NULL UNIQUE DEFAULT (UPPER(MD5(RAND()))),
  owner VARCHAR(64) NOT NULL,
  name VARCHAR(32) NOT NULL,
  app VARCHAR(32) NOT NULL, 
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  INDEX app (app),
  INDEX owner (owner)
);

CREATE TABLE reqs (
  `key` INT NOT NULL UNIQUE,
  last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  total INT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (`key`) REFERENCES `keys`(id)
);

CREATE TABLE reqs_daily (
  `key` INT NOT NULL,
  day VARCHAR(32) NOT NULL,
  total INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`key`, day),
  FOREIGN KEY (`key`) REFERENCES `keys`(id)
);

CREATE TABLE reqs_monthly (
  `key` INT NOT NULL,
  month VARCHAR(32) NOT NULL,
  total INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`key`, month),
  FOREIGN KEY (`key`) REFERENCES `keys`(id)
);