name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: snapshot-labs/actions/.github/workflows/test.yml@main
    secrets: inherit
    with:
      mysql_database_name: keycard_test
